### ISSUE TITLE
Failed to run migrations.: There was an error processing a remote WS request

### ISSUE THREAD

**Issue by snarkipus** [Odonno/surrealdb-migrations#20]
## Issue:
Occurs when attempting to run migrations over secure websockets (Wss).

## Likely Cause:
Most likely caused by [#1949](https://github.com/surrealdb/surrealdb/issues/1949) which has been [fixed upstream](https://github.com/surrealdb/surrealdb/pull/1960) (bad tls feature flag). The fix has been merged, but I don't think you get it with beta-9. 

## Workaround/Resolution:
Build surrealdb from latest commit or wait for beta-10.

**Comment by Odonno** [comment]
Hi Matt,

Indeed, this is related to this issue. I do not know when the beta-10 will be released but in order to fix this issue and if a new version is not available before the next release of `surrealdb-migrations`, I will target the surrealdb repository directly to get the fix.

I will get back to you when this is done.

**Comment by Odonno** [comment]
Hi again Matt,

With the help of @Roms1383, this problem is now fixed by targeting the `main` branch of surrealdb. However, I cannot publish the crate without targeting a crate specific version. 

So, until `surrealdb` releases the beta-10, I cannot publish/release a crate to fix this issue. I am as frustrated as you are but my hands are tied. Let's hope beta-10 comes soon.

**Comment by Odonno** [comment]
I tested it just now with a new surrealdb instance deployed using v1.0.0. I can apply migrations over HTTPS or WSS.

You can download the latest release of `surrealdb-migrations` using the following command: 

```
cargo install surrealdb-migrations@1.0.0-preview.1
```
