### ISSUE TITLE
Error listing schemas directory

### ISSUE THREAD

**Issue by johansmitsnl** [Odonno/surrealdb-migrations#48]
**Describe the bug**
`Error listing schemas directory`

**To Reproduce**
```rs
match MigrationRunner::new(&surrealdb).up().await {
        Ok(_) => tracing::info!("Migrations done"),
        Err(err) => panic!("Failed to apply migrations: {err}"),
    };
```

**Expected behavior**
Migrate

**Information**
Please complete the following information and remove the unnecessary ones.

- SurrealDB version: 1.0.0-beta.9+20230402.5eafebd for linux on x86_64
- surrealdb-migration version: 0.9.12

**Comment by Odonno** [comment]
Hi Johan,

Are you able to share a reproducible project that can lead to this error? The error is pretty clear, it says it can't find a `schemas` folder in your project but I cannot see the reason why at the moment.

Thank you.

**Comment by johansmitsnl** [comment]
Know you mention this. This is a release build of the app that it is shipped to a other location to run. In that location there are no folders of the migration present since the app is in `/usr/bin`. This explains the error.
Can't you embed the folders that are needed?

**Comment by Odonno** [comment]
Yes, you can perfectly run your app in an embedded context. There is a function called `load_files` which will use embedded folder instead of the running filesystem folder.

Check the docs here: https://docs.rs/surrealdb-migrations/latest/surrealdb_migrations/struct.MigrationRunner.html#method.load_files

If you want a more concrete example, there is a sample app in this project. It is designed to run in a WASM embedded context but it will be similar to any other kind of embedded context. The sample can be found on this repository here: https://github.com/Odonno/surrealdb-migrations/blob/main/samples/wasm/rsw-hello/src/lib.rs

**Comment by Odonno** [comment]
Yes, I put my migration files inside `db` folder in my sample app and I target it this way https://github.com/Odonno/surrealdb-migrations/blob/0ff56498de3331c384c512a1c99b90b2a9160934/samples/wasm/rsw-hello/src/lib.rs#L23

This is because when embedding a folder, it will embed EVERYTHING in this folder. So you have to create a specific folder with only your migration files. That is if you want to optimize your app and not put your entire project inside the embedded folder. I may have not explained this part, indeed. WIll add a note somewhere to explain why it is done this way and why it is a best practice to do this.

About the scaffolding, it is in general done when your project is empty. I can totally see a use case where you want to scaffold a project based on dir property that you set in the configuraton file. Noted!

**Comment by jaymes15** [comment]
@Odonno @johansmitsnl I am till experiencing this

I am able to apply migrations locally while developing
but it breaks on my GitHub actions ci.

Here is my GitHub actions

---
name: Continuous Integration And Deployment

on:
  push:
    branches:
      - main
      - develop
      - preview
    paths:
      - 'surrealdb-migrations/**/*'

  pull_request:
    branches:
      - main
      - develop
      - preview

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make Env file
        run: mv .sample.build.env .env
      - name: Start Application
        run: docker-compose up --build -d emote_db emote_app
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Apply migrations
        uses: Odonno/surrealdb-migrations-action@v0.2.0
        with:
          address: 'http://localhost:8000/rpc'
          ns: 'test'
          db: 'test'

      - name: Test
        run: docker-compose run --rm emote_app sh -c "npm run test"

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npx prettier --check ./src && npx eslint src --fix-dry-run

  apply_migration_staging_env:
    name: Apply Db migration to staging environment
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: ${{ github.ref == 'refs/heads/develop' && contains(github.event.compare, '...') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Apply migrations
        uses: Odonno/surrealdb-migrations-action@v0.2.0
        with:
          version: 0.9.12
          address: ${{ secrets.STAGING_SURREALDB_ADDRESS }}
          ns: ${{ secrets.STAGING_SURREALDB_NS }}
          db: ${{ secrets.STAGING_SURREALDDB_DB }}
          username: ${{ secrets.STAGING_SURREALDDB_USERNAME }}
          password: ${{ secrets.STAGING_SURREALDDB_PASSWORD }}

  apply_migration_preview_env:
    name: Apply Db migration to preview environment
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: ${{ github.ref == 'refs/heads/preview' && contains(github.event.compare, '...') }}
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Apply migrations
        uses: Odonno/surrealdb-migrations-action@v0.2.0
        with:
          version: 0.9.12
          address: ${{ secrets.PREVIEW_SURREALDB_ADDRESS }}
          ns: ${{ secrets.PREVIEW_SURREALDB_NS }}
          db: ${{ secrets.PREVIEW_SURREALDDB_DB }}
          username: ${{ secrets.PREVIEW_SURREALDDB_USERNAME }}
          password: ${{ secrets.PREVIEW_SURREALDDB_PASSWORD }}

  apply_migration_production_env:
    name: Apply Db migration to production environment
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: ${{ github.ref == 'refs/heads/main' && contains(github.event.compare, '...') }}
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Apply migrations
        uses: Odonno/surrealdb-migrations-action@v0.2.0
        with:
          version: 0.9.12
          address: ${{ secrets.PROD_SURREALDB_ADDRESS }}
          ns: ${{ secrets.PROD_SURREALDB_NS }}
          db: ${{ secrets.PROD_SURREALDDB_DB }}
          username: ${{ secrets.PROD_SURREALDDB_USERNAME }}
          password: ${{ secrets.PROD_SURREALDDB_PASSWORD }}

**Comment by johansmitsnl** [comment]
@jaymes15 it breaks because it needs to build against the main branch.

**Comment by johansmitsnl** [comment]
I created a PR #53 that uses the 1.0.0 release.
